// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClCq5TKP8_8dn1j6maCpiVPoxfIYPzSHA',
    appId: '1:776071747219:web:61ac54f5182bcdc42c9f66',
    messagingSenderId: '776071747219',
    projectId: 'habiture-7c263',
    authDomain: 'habiture-7c263.firebaseapp.com',
    storageBucket: 'habiture-7c263.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvdu9LUR46sUROJvDXu8sevCoXducEzMg',
    appId: '1:776071747219:android:af18b9194324392d2c9f66',
    messagingSenderId: '776071747219',
    projectId: 'habiture-7c263',
    storageBucket: 'habiture-7c263.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-kW3wZQnveO3nnlVKoHc6Dc7tb4C-9Go',
    appId: '1:776071747219:ios:79a6777f1c1b2b152c9f66',
    messagingSenderId: '776071747219',
    projectId: 'habiture-7c263',
    storageBucket: 'habiture-7c263.firebasestorage.app',
    iosBundleId: 'com.example.habiture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-kW3wZQnveO3nnlVKoHc6Dc7tb4C-9Go',
    appId: '1:776071747219:ios:79a6777f1c1b2b152c9f66',
    messagingSenderId: '776071747219',
    projectId: 'habiture-7c263',
    storageBucket: 'habiture-7c263.firebasestorage.app',
    iosBundleId: 'com.example.habiture',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClCq5TKP8_8dn1j6maCpiVPoxfIYPzSHA',
    appId: '1:776071747219:web:62163fb13490668a2c9f66',
    messagingSenderId: '776071747219',
    projectId: 'habiture-7c263',
    authDomain: 'habiture-7c263.firebaseapp.com',
    storageBucket: 'habiture-7c263.firebasestorage.app',
  );
}
